-- ============================================
-- Section 26 - Database Schema
-- ============================================

DROP TABLE IF EXISTS students CASCADE;
DROP TABLE IF EXISTS courses CASCADE;

-- ============================================
-- Courses
-- ============================================

CREATE TABLE courses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    language_name VARCHAR(100) NOT NULL,
    name VARCHAR(150) NOT NULL,
    language_level VARCHAR(50) NOT NULL,
    description TEXT,
    teacher_id INTEGER
);

-- ============================================
-- Students
-- ============================================

CREATE TABLE students (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    course_id INTEGER,
    payment_status VARCHAR(30) NOT NULL DEFAULT 'pending',

    CONSTRAINT students_course_fk
        FOREIGN KEY (course_id)
        REFERENCES courses(id)
);

-- ============================================
-- Indexes
-- ============================================

CREATE INDEX students_course_id_idx
ON students(course_id);

CREATE INDEX students_payment_status_idx
ON students(payment_status);

CREATE INDEX courses_language_name_idx
ON courses(language_name);